= 七种结构型设计模式

=== 适配器模式

====
.概述
将一个类的接口转换成客户希望的另外一个接口。Adapter模式使得原本由于接口不兼容而不能一起工作的那些类可以在一起工作。

.解决的问题
即Adapter模式使得原本由于接口不兼容而不能一起工作的那些类可以在一起工作。非常简单易懂。
====
.模式中的角色

* 目标接口（Target）：客户所期待的接口。目标可以是具体的或抽象的类，也可以是接口。
* 需要适配的类（Adaptee）：需要适配的类或适配者类。
* 适配器（Adapter）：通过包装一个需要适配的对象，把原接口转换成目标接口。

=== 装饰器模式

====
定义：动态给一个对象添加一些额外的职责,就象在墙上刷油漆.使用Decorator模式相比用生成子类方式达到功能的扩充显得更为灵活。
设计初衷:通常可以使用继承来实现功能的拓展,如果这些需要拓展的功能的种类很繁多,那么势必生成很多子类,增加系统的复杂性,同时,使用继承实现功能拓展,我们必须可预见这些拓展功能,这些功能是编译时就确定了,是静态的

要点：装饰者与被装饰者拥有共同的超类，继承的目的是继承类型，而不是行为
====

* 个人见解：其实装饰器模式很好理解，就是把被装饰的类设为全局变量，以构造函数传值，内部定义方法对这个变量的方法进行改造或增加新内容。比较典型的就是并发包里流的架构

=== 代理模式


代理模式分静态代理和动态代理，两者要实现的功能差异还是挺大的


====
.静态代理
定义 ：对一些对象提供代理，以控制对象的访问。

.见解
其实静态代理和装饰模式基本没什么区别，无非是被定义概念的人给限定死了。限制死的主要是实现方式和功能类型。两者可以互相实现对方的功能。
====

====
.动态代理
动态的创建一个虚的代理类。分jdk动态代理和cglib动态代理。具体不详细赘述。

.场景
动态代理是框架架构中应用最广泛的一个设计模式，主要是用来为接口或者类创建虚的对象类（定义或改造方法），并实例化，业务开发基本用不到。个人认为，一个不能熟练应用动态代理的研发都最多只能算是入门，唯有熟练掌握甚至说精通，才可以认为是到了入室的境界。
====

=== 外观模式（门面模式）

比较简单创建一个接待员对象作为门面，客户端通过该门面访问其封装的各个模块的方法

.门面模式的优点
* 松散耦合： 门面模式松散了客户端与子系统的耦合关系，让子系统内部的模块能更容易扩展和维护。
* 简单易用： 门面模式让子系统更加易用，客户端不再需要了解子系统内部的实现，也不需要跟众多子系统内部的模块进行交互，只需要跟门面类交互就可以了。
* 更好的划分访问层次：通过合理使用Facade，可以帮助我们更好地划分访问的层次。有些方法是对系统外的，有些方法是系统内部使用的。把需要暴露给外部的功能集中到门面中，这样既方便客户端使用，也很好地隐藏了内部的细节。

=== 桥接模式

NOTE: 具体内容太过简单，不详细解释。

.个人见解
桥接模式也比较简单，举个例子，A、B两种对象，若在A对象里使用B对象，B类建一个父接口，A中设置一个B的父接口类型的全局变量，如此结构更清晰。通过提供抽象化和实现化之间的桥接结构，来实现二者的解耦。

=== 组合模式

NOTE: 具体内容太过简单，不详细解释。

.场景
当发现需求中是体现部分与整体层次结构时，以及你希望用户可以忽略组合对象与单个对象的不同，统一地使用组合结构中的所有对象时，就应该考虑组合模式了
.实现方式
对象内设一个集合变量，用以存储该对象的所有部件。

=== 享元模式

TIP: 这个就简单了，建一个map，隐式创建

场景: 数据库连接池，线程池等即是用享元模式的应用